# Generated by Django 5.1.6 on 2025-02-08 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('sender_name', models.CharField(db_column='WYDM_YName', max_length=100)),
                ('recipient_name', models.CharField(db_column='WYDM_DName', max_length=100)),
                ('slug', models.SlugField(db_column='WYDM_PathName', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('option', models.IntegerField(db_column='WYDM_OptionTaken')),
            ],
            options={
                'db_table': 'WYDM_T1',
            },
        ),
    ]
