# Generated by Django 5.1.6 on 2025-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wydm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(db_column='WYDM_Message', default=''),
        ),
    ]
